AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Atlassian::Opsgenie::Team resource type

Globals:
  Function:
    Timeout: 10  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.atlassian.opsgenie.integration.HandlerWrapper::handleRequest
      Runtime: java11
      CodeUri: opsgenie_integration/target/atlassian-opsgenie-integration-handler-2.1.2.jar
      Timeout: 60

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.atlassian.opsgenie.integration.HandlerWrapper::testEntrypoint
      Runtime: java11
      CodeUri: opsgenie_integration/target/atlassian-opsgenie-integration-handler-2.1.2.jar
      Timeout: 60